export const STORAGE_KEYS = {
  anonymousUserId: "introbase_anonymous_user_id",
  sessionId: "introbase_session_id",
  currentAnalysis: "introbase_current_analysis",
  demoCurrentAnalysis: "introbase_demo_current_analysis",
  analysisDiagnosticsStats: "introbase_analysis_diagnostics_stats",
  demoAnalysisDiagnosticsStats: "introbase_demo_analysis_diagnostics_stats",
  importDraft: "introbase_import_draft",
  demoImportDraft: "introbase_demo_import_draft",
  importDraftMessages: "introbase_import_draft_messages",
  demoImportDraftMessages: "introbase_demo_import_draft_messages",
  previousImportMessages: "introbase_previous_import_messages",
  demoPreviousImportMessages: "introbase_demo_previous_import_messages",
  boardDeletedMessageIds: "introbase_board_deleted_message_ids",
  demoBoardDeletedMessageIds: "introbase_demo_board_deleted_message_ids",
  boardMessageOrder: "introbase_board_message_order",
  demoBoardMessageOrder: "introbase_demo_board_message_order",
  appSidebarCollapsed: "introbase_app_sidebar_collapsed",
  savedContacts: "introbase_saved_contacts",
  demoSavedContacts: "introbase_demo_saved_contacts",
  followups: "introbase_followups",
  demoFollowups: "introbase_demo_followups",
  hasSeenFeedbackModal: "introbase_has_seen_feedback_modal",
} as const;
